src/objects/Inseminacion__c.object
<CustomObject>
    <description>Inseminaciones que se le hacen a cada vaca. Este servicio será importante, dado que le permitirá al tambero controlar la cantidad de inseminaciones que le hacen a una vaca, y a partir de las mismas notificar cuando una vaca estará en estado de pre-parto.</description>
    <fields>
        <fullName>Efectiva__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Se chequea esta box si la inseminación fue efectiva.</description>
        <inlineHelpText>Tickear si &apos;agarró&apos;</inlineHelpText>
        <label>Efectiva</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Fecha en la que se realiza la inseminación</description>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vaca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Una inseminación pertenece a una vaca</description>
        <label>Vaca</label>
        <referenceTo>Vaca__c</referenceTo>
        <relationshipLabel>Inseminaciones</relationshipLabel>
        <relationshipName>Inseminaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inseminación</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Inseminación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inseminaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vaca__c.object
<CustomObject>
    <description>Vacas que se manejan en el campo.</description>
    <label>Vaca</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vaca Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InseminacionesSinEfectoService.cls
public class InseminacionesSinEfectoService {
                
                    /**
                    * @description
                    * @return true su la vaca no ha tenido mas de tres inseminaciones seguidas sin efecto 
                    */
                        @AuraEnabled
                        public static Boolean isVacaInseminable(Id vacaId){
                            try{
                                System.debug('isVacaInseminable, vaca id: '+vacaId); 
                                /*Query que me trae las tres ultimas inseminaciones de la vaca */
                                List<Inseminacion__c> inseminaciones = [select id, efectiva__c from Inseminacion__c where vaca__c =:vacaId
                                                                        order by fecha__c desc limit 3];
                                /*Aca filtro por inseminacion no efectiva*/    
                                integer count = 0;
                                    for(integer i=0; i<inseminaciones.size(); i++){
                                        if (inseminaciones[i].efectiva__c==false){
                                            count++;
                                        }
                                    }
                                
                                if(count==3){
                                    return false;
                                } else{
                                    return true;
                                }
           
                        }catch(Exception e){
                        throw new AuraHandledException('Error doing the query. Error: '+e.getMessage());
                    }
            }
    }