src/objects/Paricion__c.object
<CustomObject>
    <description>Pariciones que tendrá una vaca.</description>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fecha_en_pre_parto__c</fullName>
        <label>Fecha en pre-parto</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vaca__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>La parición pertenece a una vaca</description>
        <label>Vaca</label>
        <referenceTo>Vaca__c</referenceTo>
        <relationshipLabel>Pariciones</relationshipLabel>
        <relationshipName>Pariciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parición</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Parición</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pariciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vaca__c.object
<CustomObject>
    <description>Vacas que se manejan en el campo.</description>
    <label>Vaca</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vaca Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/schedulableClassTest.cls
/*Esta clase corre un proceso todos los dias a la 1 y chequea si hay vacas en parto 
o pre-parto para avisar. Se ejecuta de la siguiente manera: 
System.schedule('Daily', '0 0 1 * * ?', new schedulableClassTest()); */
public class schedulableClassTest implements Schedulable {
   
    public void execute(SchedulableContext ctx) {
    	List<Paricion__c> pariciones = [Select id, Fecha__c, Fecha_en_pre_parto__c, 
                                                Vaca__c from paricion__c];	
        MyUtils.reminderParto_PreParto(pariciones);
    }
    
}